//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion.Resources.RefCursors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplicacion.Resources.RefCursors.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admsrv_beneficiario.
        /// </summary>
        public static string admsrv_beneficiario {
            get {
                return ResourceManager.GetString("admsrv_beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admsrv_extractouninetreg.
        /// </summary>
        public static string admsrv_extractouninetreg {
            get {
                return ResourceManager.GetString("admsrv_extractouninetreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admsrv_extractouninetverifc.
        /// </summary>
        public static string admsrv_extractouninetverifc {
            get {
                return ResourceManager.GetString("admsrv_extractouninetverifc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admsrv_persona.
        /// </summary>
        public static string admsrv_persona {
            get {
                return ResourceManager.GetString("admsrv_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_facturaanulada.
        /// </summary>
        public static string pldsrv_facturaanulada {
            get {
                return ResourceManager.GetString("pldsrv_facturaanulada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_facturadosificacion.
        /// </summary>
        public static string pldsrv_facturadosificacion {
            get {
                return ResourceManager.GetString("pldsrv_facturadosificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_facturareg.
        /// </summary>
        public static string pldsrv_facturareg {
            get {
                return ResourceManager.GetString("pldsrv_facturareg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_facturavalidareg.
        /// </summary>
        public static string pldsrv_facturavalidareg {
            get {
                return ResourceManager.GetString("pldsrv_facturavalidareg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planilladet_ben.
        /// </summary>
        public static string pldsrv_planilladet_ben {
            get {
                return ResourceManager.GetString("pldsrv_planilladet_ben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planilladet_per.
        /// </summary>
        public static string pldsrv_planilladet_per {
            get {
                return ResourceManager.GetString("pldsrv_planilladet_per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planillanegativa.
        /// </summary>
        public static string pldsrv_planillanegativa {
            get {
                return ResourceManager.GetString("pldsrv_planillanegativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planillapago.
        /// </summary>
        public static string pldsrv_planillapago {
            get {
                return ResourceManager.GetString("pldsrv_planillapago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planillas.
        /// </summary>
        public static string pldsrv_planillas {
            get {
                return ResourceManager.GetString("pldsrv_planillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrv_planillasporpagar.
        /// </summary>
        public static string pldsrv_planillasporpagar {
            get {
                return ResourceManager.GetString("pldsrv_planillasporpagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pldsrvcmb_planilla.
        /// </summary>
        public static string pldsrvcmb_planilla {
            get {
                return ResourceManager.GetString("pldsrvcmb_planilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subplanificacion.
        /// </summary>
        public static string subsrv_subplanificacion {
            get {
                return ResourceManager.GetString("subsrv_subplanificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subplanificaciondetalle.
        /// </summary>
        public static string subsrv_subplanificaciondetalle {
            get {
                return ResourceManager.GetString("subsrv_subplanificaciondetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subplanificacionhijo.
        /// </summary>
        public static string subsrv_subplanificacionhijo {
            get {
                return ResourceManager.GetString("subsrv_subplanificacionhijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subplanificacionplanilla.
        /// </summary>
        public static string subsrv_subplanificacionplanilla {
            get {
                return ResourceManager.GetString("subsrv_subplanificacionplanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subplanificacionplanillaapr.
        /// </summary>
        public static string subsrv_subplanificacionplanillaapr {
            get {
                return ResourceManager.GetString("subsrv_subplanificacionplanillaapr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subtitularbeneficiarioliberado.
        /// </summary>
        public static string subsrv_subtitularbeneficiarioliberado {
            get {
                return ResourceManager.GetString("subsrv_subtitularbeneficiarioliberado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_subtitularliberado.
        /// </summary>
        public static string subsrv_subtitularliberado {
            get {
                return ResourceManager.GetString("subsrv_subtitularliberado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subsrv_titularforbeneficiario.
        /// </summary>
        public static string subsrv_titularforbeneficiario {
            get {
                return ResourceManager.GetString("subsrv_titularforbeneficiario", resourceCulture);
            }
        }
    }
}
